config/routes.rb
# frozen_string_literal: true

# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
#
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
#
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.

Rails.application.routes.draw do
  get '/health_check', to: 'health_check#all'

  # Error routes.
  match '/401', to: 'errors#unauthorized', via: :all, as: :unauthorized
  match '/404', to: 'errors#not_found', via: :all, as: :not_found
  match '/500', to: 'errors#internal_error', via: :all, as: :internal_error

  # Signin/Signup routes.
  get '/signin', to: 'sessions#signin', as: :signin
  get '/signup', to: 'sessions#new', as: :signup
  post '/signup', to: 'users#create', as: :create_user
  get '/ldap_signin', to: 'sessions#ldap_signin', as: :ldap_signin

  # Redirect to terms page
  match '/terms', to: 'users#terms', via: [:get, :post]

  # Admin resouces
  resources :admins, only: [:index]

  scope '/admins' do
    # Panel Tabs
    get '/rooms', to: 'admins#server_rooms', as: :admin_rooms
    get '/recordings', to: 'admins#server_recordings', as: :admin_recordings
    get '/site_settings', to: 'admins#site_settings', as: :admin_site_settings
    get '/room_configuration', to: 'admins#room_configuration', as: :admin_room_configuration
    get '/roles', to: 'admins#roles', as: :admin_roles
    # Manage Users
    get '/edit/:user_uid', to: 'admins#edit_user', as: :admin_edit_user
    post '/ban/:user_uid', to: 'admins#ban_user', as: :admin_ban
    post '/unban/:user_uid', to: 'admins#unban_user', as: :admin_unban
    post '/invite', to: 'admins#invite', as: :invite_user
    post '/approve/:user_uid', to: 'admins#approve', as: :admin_approve
    get '/reset', to: 'admins#reset', as: :admin_reset
    post '/undelete', to: 'admins#undelete', as: :admin_undelete
    post '/merge/:user_uid', to: 'admins#merge_user', as: :merge_user
    # Site Settings
    post '/update_settings', to: 'admins#update_settings', as: :admin_update_settings
    post '/registration_method', to: 'admins#registration_method', as: :admin_change_registration
    post '/coloring', to: 'admins#coloring', as: :admin_coloring
    post '/clear_cache', to: 'admins#clear_cache', as: :admin_clear_cache
    post '/clear_auth', to: 'admins#clear_auth', as: :admin_clear_auth
    post '/log_level', to: 'admins#log_level', as: :admin_log_level
    # Room Configuration
    post '/update_room_configuration', to: 'admins#update_room_configuration', as: :admin_update_room_configuration
    # Roles
    post '/role', to: 'admins#new_role', as: :admin_new_role
    patch 'roles/order', to: 'admins#change_role_order', as: :admin_roles_order
    post '/role/:role_id', to: 'admins#update_role', as: :admin_update_role
    delete 'role/:role_id', to: 'admins#delete_role', as: :admin_delete_role
  end

  scope '/themes' do
    get '/primary', to: 'themes#index', as: :themes_primary
  end

  # Event Registration
  get '/register', to: 'register#index'
  get '/register/:event_slug', to: 'register#event'
  post '/register/:event_slug', to: 'register#event'
  get '/eventinfo/:event_slug', to: 'register#eventinfo'
  get '/registeradmin/:event_slug', to: 'register#admin'
  post '/registeradmin/:event_slug', to: 'register#admin'
  get '/post/:event_slug', to: 'register#admin'
  post '/ingest/:event_slug', to: 'ingest#ingest'

  # Password reset resources.
  resources :password_resets, only: [:new, :create, :edit, :update]

  # Account activation resources
  scope '/account_activations' do
    get '/', to: 'account_activations#show', as: :account_activation
    get '/edit', to: 'account_activations#edit', as: :edit_account_activation
    post '/resend', to: 'account_activations#resend', as: :resend_email
  end

  # User resources.
  scope '/u' do
    # Handles login of greenlight provider accounts.
    post '/login', to: 'sessions#create', as: :create_session

    # Log the user out of the session.
    post '/logout', to: 'sessions#destroy'

    # Account management.
    get '/:user_uid/edit', to: 'users#edit', as: :edit_user
    get '/:user_uid/change_password', to: 'users#change_password', as: :change_password
    get '/:user_uid/delete_account', to: 'users#delete_account', as: :delete_account
    post '/:user_uid/edit', to: 'users#update', as: :update_user
    post '/:user_uid/change_password', to: 'users#update_password', as: :update_password
    delete '/:user_uid', to: 'users#destroy', as: :delete_user

    # All user recordings
    get '/:user_uid/recordings', to: 'users#recordings', as: :get_user_recordings
  end

  # Handles Omniauth authentication.
  match '/auth/:provider/callback', to: 'sessions#omniauth', via: [:get, :post], as: :omniauth_session
  get '/auth/failure', to: 'sessions#omniauth_fail'
  post '/auth/ldap', to: 'sessions#ldap', as: :ldap_callback

  # Users who can't create rooms
  get '/rooms', to: 'rooms#cant_create_rooms', as: :cant_create_rooms

  # Room resources.
  resources :rooms, only: [:create, :show, :destroy], param: :room_uid, path: '/'

  # Join a room by UID
  post '/room/join', to: 'rooms#join_specific_room', as: :join_room

  # Extended room routes.
  scope '/:room_uid' do
    post '/', to: 'rooms#join'
    patch '/', to: 'rooms#update', as: :update_room
    get '/room_settings', to: 'rooms#room_settings'
    post '/update_settings', to: 'rooms#update_settings'
    post '/update_shared_access', to: 'rooms#shared_access', as: :room_shared_access
    delete '/remove_shared_access', to: 'rooms#remove_shared_access', as: :room_remove_shared_access
    get '/shared_users', to: 'rooms#shared_users', as: :room_shared_users
    post '/start', to: 'rooms#start', as: :start_room
    get '/logout', to: 'rooms#logout', as: :logout_room
    post '/login', to: 'rooms#login', as: :login_room
  end

  # Recording operations routes
  scope '/:meetingID' do
    # Manage recordings
    scope '/:record_id' do
      post '/', to: 'recordings#update', as: :update_recording
      patch '/', to: 'recordings#rename', as: :rename_recording
      delete '/', to: 'recordings#delete', as: :delete_recording
    end
  end

  root to: 'main#index'
end

app/views/shared/modals/_create_role_modal.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="modal fade" id="createRoleModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content text-center">
      <div class="modal-body">
        <div class="card-body p-6">
          <div class="card-title">
            <h3><%= t("modal.create_role.title") %></h3>
          </div>

          <%= form_for(:role, url: admin_new_role_path) do |f| %>
            <div class="input-icon mb-2">
              <span class="input-icon-addon">
                <i class="fas fa-user-tag"></i>
              </span>
              <%= f.text_field :name, id: "createRoleName", class: "form-control text-center", placeholder: t("modal.create_role.name_placeholder"), autocomplete: :off, required: true %>
              <div class="invalid-feedback text-left"><%= t("modal.create_role.not_blank") %></div>
            </div>
            <div class="mt-4">
                <%= f.submit t("modal.create_role.create"), class: "btn btn-primary btn-block" %>
            </div>
          <% end %>
        </div>
        <div class="card-footer">
          <p><%= t("modal.create_role.footer_text") %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/modals/_create_room_modal.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>
<div class="modal fade" id="createRoomModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content text-center">
      <div class="modal-body">
        <div class="card-body p-sm-6">
          <div class="card-title">
            <h3 class="create-only"><%= t("modal.create_room.title") %></h3>
            <h3 class="update-only"><%= t("modal.room_settings.title") %></h3>
          </div>

          <%= form_for(:room, url: rooms_path) do |f| %>
            <div class="input-icon mb-2">
              <span class="input-icon-addon">
                <i class="fas fa-chalkboard-teacher"></i>
              </span>
              <%= f.text_field :name, id: "create-room-name", class: "form-control text-center", value: "", placeholder: t("modal.create_room.name_placeholder"), autocomplete: :off %>
              <div class="invalid-feedback text-left"><%= t("modal.create_room.not_blank") %></div>
            </div>

            <div class="input-icon mb-2">
              <span onclick="generateAccessCode()" class="input-icon-addon allow-icon-click cursor-pointer">
                <i class="fas fa-dice"></i>
              </span>
              <%= f.label :access_code, t("modal.create_room.access_code_placeholder"), id: "create-room-access-code", class: "form-control" %>
              <%= f.hidden_field :access_code %>
              <span onclick="ResetAccessCode()" class="input-icon-addon allow-icon-click cursor-pointer">
                <i class="far fa-trash-alt"></i>
              </span>
            </div>

            <div class="input-icon mb-2" style="display: none">
              <span class="input-icon-addon">
                <i class="fas fa-sign-language"></i>
              </span>
              <%= f.text_field :matrix, id: "create-room-matrix", class: "form-control text-center", value: "", placeholder: "Matrix Room: akademy-meet", autocomplete: :off %>
            </div>
            <p>If room is not configured, a default of #akademy-meet:kde.org will be used. Rooms must exist on the KDE Matrix Homeserver.</p>

            <% mute = room_configuration("Room Configuration Mute On Join") %>
            <% if mute != "disabled" %>
              <label class="custom-switch pl-0 mt-3 mb-3 w-100 text-left d-inline-block <%= "enabled-setting" if mute == "enabled" %>">
                <span class="custom-switch-description"><%= t("modal.room_settings.mute")%></span>
                <%= f.check_box :mute_on_join, class: "custom-switch-input", data: { default: mute == "enabled" }, checked: false %>
                <span class="custom-switch-indicator float-right cursor-pointer"></span>
              </label>
            <% end %>

            <% require_approval = room_configuration("Room Configuration Require Moderator") %>
            <% if require_approval != "disabled" %>
              <label class="custom-switch pl-0 mt-3 mb-3 w-100 text-left d-inline-block <%= "enabled-setting" if require_approval == "enabled" %>">
                <span class="custom-switch-description"><%= t("modal.room_settings.require_approval")%></span>
                <%= f.check_box :require_moderator_approval, class: "custom-switch-input", data: { default: require_approval == "enabled" }, checked: false %>
                <span class="custom-switch-indicator float-right cursor-pointer"></span>
              </label>
            <% end %>
            
            <% any_start = room_configuration("Room Configuration Allow Any Start") %>
            <% if any_start != "disabled" %>
              <label class="custom-switch pl-0 mt-3 mb-3 w-100 text-left d-inline-block <%= "enabled-setting" if any_start == "enabled" %>">
                <span class="custom-switch-description"><%= t("modal.room_settings.start")%></span>
                <%= f.check_box :anyone_can_start, class: "custom-switch-input", data: { default: any_start == "enabled" }, checked: false %>
                <span class="custom-switch-indicator float-right cursor-pointer"></span>
              </label>
            <% end %>

            <% moderator = room_configuration("Room Configuration All Join Moderator") %>
            <% if moderator != "disabled" %>
              <label class="custom-switch pl-0 mt-3 mb-3 w-100 text-left d-inline-block <%= "enabled-setting" if moderator == "enabled" %>">
                <span class="custom-switch-description"><%= t("modal.room_settings.join_moderator")%></span>
                <%= f.check_box :all_join_moderator, class: "custom-switch-input", data: { default: moderator == "enabled" }, checked: false %>
                <span class="custom-switch-indicator float-right cursor-pointer"></span>
              </label>
            <% end %>

            <label id="auto-join-label" class="create-only custom-switch pl-0 mt-3 mb-3 w-100 text-left d-inline-block">
              <span class="custom-switch-description"><%= t("modal.create_room.auto_join") %></span>
              <%= f.check_box :auto_join, class: "custom-switch-input", checked: false %>
              <span class="custom-switch-indicator float-right cursor-pointer"></span>
            </label>
          <div class="mt-4">
            <%= f.submit t("modal.create_room.create"), class: "create-only btn btn-primary btn-block" %>
            <%= f.submit t("modal.room_settings.update"), class: "update-only btn btn-primary btn-block" %>
          </div>
          <% end %>
        </div>
        <div class="card-footer">
          <p class="create-only"><%= t("modal.create_room.free_delete") %></p>
          <p class="update-only"><%= t("modal.room_settings.footer_text") %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/modals/_delete_account_modal.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="modal fade" id="deleteAccountModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content text-center">
      <div class="modal-body">
        <div class="card-body p-6">
          <div class="card-title">
            <h3><%= t("modal.delete_account.confirm") %></h3>
          </div>

          <button type="button" class="btn btn-info my-1 btn-del-room" data-dismiss="modal">
            <%= t("modal.delete_account.keep") %>
          </button>

          <%= button_to delete_location, method: :delete, id: "delete-confirm", class: "btn btn-danger my-1 btn-del-room", disabled:"", "data-disable": "" do %>
            <%= t("modal.delete_account.delete") %>
          <% end %>

        </div>
        <div class="card-footer">
          <label class="custom-control custom-checkbox">
            <input id="delete-checkbox" type="checkbox" class="custom-control-input">
            <p id="perm-delete" class="custom-control-label"><%= t("modal.delete_account.warning").html_safe %></p>
            <p id="delete-warning" class="custom-control-label"><%= t("modal.delete_account.delete_warning").html_safe %></p>
          </label>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/modals/_delete_room_modal.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="modal fade" id="deleteRoomModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content text-center">
      <div class="modal-body">
        <div class="card-body p-6">
          <div class="card-title">
            <h3 id="delete-header"></h3>
          </div>

          <button type="button" class="btn btn-info my-1 btn-del-room" data-dismiss="modal">
            <%= t("modal.delete_room.keep") %>
          </button>

          <%= button_to "/", method: :delete, id: "delete-confirm", class: "btn btn-danger my-1 btn-del-room", "data-disable": "" do %>
            <%= t("modal.delete_room.delete") %>
          <% end %>

        </div>
        <div class="card-footer">
          <p id="delete-footer">
            <%= t("modal.delete_room.warning").html_safe %>
            <%= t("modal.delete_room.recording_warning", recordings_num:"").html_safe %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/modals/_invite_user_modal.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="modal fade" id="inviteModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content text-center">
      <div class="modal-body">
        <div class="card-body p-6">
          <div class="card-title">
            <h3><%= t("modal.invite_user.title") %></h3>
          </div>

          <%= form_for(:invite_user, url: invite_user_path) do |f| %>
            <div class="input-icon mb-2">
              <span class="input-icon-addon">
                <i class="fas fa-envelope"></i>
              </span>
              <%= f.text_field :email, class: "form-control", value: "", placeholder: t("modal.invite_user.email_placeholder"), autocomplete: :off %>
              <div class="invalid-feedback text-left"><%= t("modal.invite_user.not_blank") %></div>
            </div>
          <div class="mt-4">
            <%= f.submit t("modal.invite_user.send"), class:"btn btn-primary btn-block" %>
          </div>
          <% end %>
        </div>
        <div class="card-footer">
          <p><%= t("modal.invite_user.footer") %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/modals/_merge_user_modal.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="modal fade" id="mergeUserModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content text-center">
      <div class="modal-body">
        <div class="card-body p-6">
          <div class="card-title">
            <h3><%= t("modal.merge_user.title") %></h3>
          </div>
          <select class="selectpicker" title="<%= t("modal.share_access.select") %>" data-live-search="true" data-virtual-scroll="true" >
            <% @user_list.each do |user| %>
                <option value="<%= { uid: user.uid, email: user.email, name: user.name }.to_json %>" data-subtext="<%= user.email %>" ><%= user.name %></option>
              <% end %>
          </select>
          <div class="mt-5 text-left row">
            <div class="list-group-item col-6 text-center">
              <label class="form-label text-primary"><%= t("modal.merge_user.from") %></label>
               <div id="merge-from"></div>
            </div>
            <i id="merge-account-arrow" class="fas fa-2x fa-arrow-circle-right text-primary"></i>
            <div class="list-group-item col-6 text-center">
              <label class="form-label text-primary"><%= t("modal.merge_user.to") %></label>
               <div id="merge-to"></div>
            </div>
          </div>
          <div class="mt-6">
            <button id="merge-save-access" class="btn btn-primary btn-block" onclick="mergeUsers()" ><%= t("modal.merge_user.save") %></button>
            <button class="btn btn-secondary text-primary btn-block" onclick="$('#mergeUserModal').modal('hide')"><%= t("modal.merge_user.cancel") %></button>
          </div>
        </div>
        <div class="card-footer">
          <p><%= t("modal.merge_user.footer") %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/modals/_remove_access_modal.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="modal fade" id="removeAccessModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content text-center">
      <div class="modal-body">
        <div class="card-body p-6">
          <div class="card-title">
            <h3><%= t("modal.remove_shared.title")%></h3>
          </div>

          <%= button_to "/", method: :delete, id: "remove-shared-confirm", class: "btn btn-danger my-1 btn-del-room" do %>
            <%= hidden_field_tag :user_id, current_user.id %>
            <%= t("modal.remove_shared.delete") %>
          <% end %>

        </div>
        <div class="card-footer">
          <p id="delete-footer">
            <%= t("modal.remove_shared.warning").html_safe %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/modals/_share_room_modal.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="modal fade" id="shareRoomModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content text-center">
      <div class="modal-body">
        <div class="card-body p-6">
          <div class="card-title">
            <h3><%= t("modal.share_access.title") %></h3>
          </div>
          <select class="selectpicker" title="<%= t("modal.share_access.select") %>" data-live-search="true" data-virtual-scroll="true" >
            <% @user_list.each do |user| %>
                <option value="<%= user.uid %>" data-subtext="<%= user.uid %>" ><%= user.name %></option>
              <% end %>
          </select>
          <div class="mt-5 text-left">
            <label class="form-label"><%= t("modal.share_access.list") %></label>
            <ul id="user-list" class="list-group">
            </ul>
          </div>
          <div class="mt-6">
            <button id="save-access" class="btn btn-primary btn-block" onclick="saveAccessChanges()" ><%= t("modal.share_access.save") %></button>
            <button class="btn btn-secondary text-primary btn-block" onclick="$('#shareRoomModal').modal('hide')"><%= t("modal.share_access.cancel_changes") %></button>
          </div>
        </div>
        <div class="card-footer">
          <p><%= t("modal.share_access.footer") %></p>
        </div>
      </div>
    </div>
  </div>
</div>